# .travis.yml
# Configure Travis CI service to build SOCI library, http://github.com/SOCI
#
# Copyright (c) 2013 Mateusz Loskot <mateusz@loskot.net>
#
# TODO: Switch to Trusty https://github.com/SOCI/soci/issues/574
dist: precise
language: cpp

# safelist
branches:
  only:
  - dev-master
  - travis-odbc

sudo: required

compiler:
  - g++

services:
  - mysql
  - postgresql

env:
  matrix:
    - SOCI_TRAVIS_BACKEND=odbc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
    packages:
      - cmake

before_install: ./scripts/travis/before_install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
